### PR TITLE
update nuget packages to support Cassandra 3.x

### PR DESCRIPTION
**Pull request by akrasov**
updated:
- CassandraCSharpDriver to 3.0.3
- Google.ProtocolBuffers to 2.4.1.555
- LZ4 to 1.0.10.93

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Might have to upgrade the build server - still running 2.x

**Comment by Aaronontheweb** [comment]
@akrasov should all of these changes be backwards compatible with Cassandra 2.0?

**Comment by Aaronontheweb** [comment]
Try using the latest off of Akka.NET core on NuGet - looks like the restores are coming from nighlties.

**Comment by cconstantin** [comment]
@Aaronontheweb had a conversation with @akrasov and we'll hold off on this and submit it together with support for persistence-query

**Pull request closed without merging**
