### PR TITLE
Enable Docker-based integration testing

### PR DESCRIPTION
**Pull request by heynickc**
PR introduces changes needed to the build scripting to enable testing against actual Cassandra instances installed on Docker containers on the TeamCity build agent.  Work in progress until alterations are made to the TeamCity build configuration to add the necessary build steps to run the new scripts in the right sequence.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@heynickc down from 15ish to 2 failing specs, nice work so far man!

**Comment by heynickc** [comment]
@Aaronontheweb thanks, I'd like to say it was something I did, but they are across the board.  8, 30, 11, 2, 6, 11.  They all pass if the `CassandraIntegrationSpec` runs first, but if `CassandraJournalSpec` runs first then there's this flaky behavior.  Troubleshooting the initialization for the tests.

**Comment by heynickc** [comment]
This is no longer a work in progress and is ready to be merged.  It represents enabling our CI server to run automated builds for this plugin against a Cassandra Docker container.  The checks don't pass currently due to what seems to be racy specs that are exacerbated with this plugin - but also show up in other plugins like SqlServer.  These flaky specs should be addressed in a subsequent PR before any other PRs are merged.

**Comment by Aaronontheweb** [comment]
@heynickc thanks for getting the CI up and running. Let's open up a PR for the racy specs inside the Akka.Persistence.TestKit and see if we can get that stuff integrated as part of the 1.2 release.

**Comment by Aaronontheweb** [comment]
If not, we can do a 1.2.1 ;)

**Pull request merged**
