### PR TITLE
Update to Akka.Persistence 1.0.5.15

### PR DESCRIPTION
**Pull request by trbngr**
The new PipeTo was breaking this plugin.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@trbngr ugh, really? - can you explain?

**Comment by Aaronontheweb** [comment]
still have a minor test failure here - going to try re-running it

**Comment by trbngr** [comment]
Method resolution was failing with MethodNotFoundException.

All test pass on my machine. I think xunit2 has problems with running too many ActorSystems in parallel. In my project, for example, I have to run it with `-maxthreads 2`

**Comment by trbngr** [comment]
Welp. That won't help us here. I just noticed that all parallelism is turned off in the test runner. :(

**Comment by trbngr** [comment]
Also you'll notice that each build will fail on different tests. I have a huge problem with this in my project too. If you know of any workarounds, I'm all ears.

**Comment by Aaronontheweb** [comment]
@trbngr going to merge it and release it for now so it solves your immediate problem. I'll bring my "death to async / await" campaign to this repo soon enough and get to the bottom of these issues

**Comment by trbngr** [comment]
Thanks, dude.

**Pull request merged**
